{{- if and (not .Values.useConfigFile) (not .Values.modem.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prom-cm1000-exporter.fullname" . }}
  labels:
    {{- include "prom-cm1000-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  modem-password: {{ .Values.modem.password | b64enc | quote }}
{{- end }}
